name: my_telco
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  bloc: ^8.1.4
  get_it: ^8.2.0
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
  connectivity_plus: ^6.1.4
  http: ^1.4.0
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  vector_graphics: ^1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  change_app_package_name: ^1.5.0
  vector_graphics_compiler: ^1.1.19

flutter:
  uses-material-design: true
  assets:
    - assets/png_files/
    - assets/mock_data/
    - path: assets/dashboard/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/forfaits/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/history/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/nav_bar/
      transformers:
        - package: vector_graphics_compiler
